// <auto-generated />
using System;
using Cuentas.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cuentas.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(CuentasDbContext))]
    partial class CuentasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cuentas")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cuentas.Domain.Clientes.ClienteReferencia", b =>
                {
                    b.Property<string>("ClienteId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cliente_id");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("SincronizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sincronizado_en");

                    b.HasKey("ClienteId");

                    b.ToTable("clientes_replicados", "cuentas");
                });

            modelBuilder.Entity("Cuentas.Domain.Cuentas.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_cuenta");

                    b.Property<decimal>("SaldoDisponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_disponible");

                    b.Property<decimal>("SaldoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_inicial");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_cuenta");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_cuentas_cliente");

                    b.HasIndex("NumeroCuenta")
                        .IsUnique()
                        .HasDatabaseName("ux_cuentas_numero");

                    b.ToTable("cuentas", "cuentas");
                });

            modelBuilder.Entity("Cuentas.Domain.Movimientos.Movimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("movimiento_id");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("SaldoDisponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_disponible");

                    b.Property<int>("Secuencia")
                        .HasColumnType("integer")
                        .HasColumnName("secuencia");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_movimiento");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_movimientos_fecha");

                    b.HasIndex("CuentaId", "Fecha", "Secuencia")
                        .HasDatabaseName("ix_movimientos_cuenta_fecha");

                    b.ToTable("movimientos", "cuentas");
                });

            modelBuilder.Entity("Shared.Infrastructure.Bandeja.MensajeSalida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("mensaje_id");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos");

                    b.Property<DateTime?>("PublicadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_en");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("tipo");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ultimo_error");

                    b.HasKey("Id");

                    b.HasIndex("CreadoEn")
                        .HasDatabaseName("ix_bandeja_salida_pendientes")
                        .HasFilter("publicado_en IS NULL");

                    b.ToTable("bandeja_salida", "cuentas");
                });

            modelBuilder.Entity("Cuentas.Domain.Movimientos.Movimiento", b =>
                {
                    b.HasOne("Cuentas.Domain.Cuentas.Cuenta", null)
                        .WithMany("Movimientos")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cuentas.Domain.Cuentas.Cuenta", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
