<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Cuentas.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Cuentas.Application/Cuentas.Application.csproj" />
    <ProjectReference Include="../../BuildingBlocks/Shared.Api/Shared.Api.csproj" />
    <ProjectReference Include="../../BuildingBlocks/Shared.Infrastructure/Shared.Infrastructure.csproj" />
  </ItemGroup>
</Project>
